version: 2.1

jobs:
  build: 
      docker:
        - image: circleci/python:3.7
      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              
        - run:
            name: install Hadolint
            command: |
            # Installation for linting dockerfile
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
              chmod +x /bin/hadolint
              
        - run:
            name: run test/lint
            command: |
              . venv/bin/activate
              make lint

workflows:
  say-hello-workflow:
    jobs:
      - build

